export { Login as ScreenLogin } from "./Login"
export { CadastrarMot as ScreenCadastrarMot } from "./CadastrarMot"
export { CadastrarEst as ScreenCadastrarEst } from "./CadastrarEst"
export { Perfil as ScreenPerfil } from "./PerfilUser"
export { CameraScreen as ScreenCamera } from "./Camera"
export { LocationScreen as ScreenLocation } from "./Location"
export { ModoUser as ScreenModo } from "./ModoUser"
export { Favoritos as ScreenFavoritos } from "./Favoritos"
export { VoucherScreen as ScreenVoucher } from "./Voucher"
export { Veiculo as ScreenVeiculo} from "./Veiculo"
export { HomeVoucherScreen as ScreenHomeVoucher } from "../screens/HomeVoucher"